language: objective-c
xcode_workspace: ./Example/VZInspector.xcworkspace
xcode_scheme: VZInspector
cache: cocoapods
podfile: ./Example/Podfile
branches:
  only:
  - master
osx_image: xcode7.3
xcode_sdk: iphonesimulator